FROM centos:6
MAINTAINER saurabh

RUN yum -y install wget && \
 yum -y install tar
 
ENV JAVA_HOME /opt/java
ENV CATALINA_HOME /opt/tomcat 
ENV PATH $PATH:$JAVA_HOME/bin:$CATALINA_HOME/bin:$CATALINA_HOME/scripts

RUN wget https://cdn.azul.com/zulu/bin/zulu8.38.0.13-ca-jre8.0.212-linux_x64.tar.gz && \
 tar -xvf zulu8.38.0.13-ca-jre8.0.212-linux_x64.tar.gz && \
 rm zulu*.tar.gz && \
 mv zulu* ${JAVA_HOME}

RUN wget http://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.40/bin/apache-tomcat-8.5.40.tar.gz && \
 tar -xvf apache-tomcat-8.5.40.tar.gz && \
 rm apache-tomcat*.tar.gz && \
 mv apache-tomcat* ${CATALINA_HOME}

#make all shellscripts inside bin executable
RUN chmod +x ${CATALINA_HOME}/bin/*sh

#Put more secured server.xml
# Removed server banner
# Added Secure flag in cookie
# Changed SHUTDOWN port and Command
 ADD server.xml ${CATALINA_HOME}/conf/

#Put more secured web.xml
# Replaced default 404, 403, 500 pages
# Will not show server version info up  on errors and exceptions
 ADD web.xml ${CATALINA_HOME}/conf/

#Remove version string from HTTP error messages
#override ServerInfo.properties in catalina.jar
 RUN mkdir -p ${CATALINA_HOME}/lib/org/apache/catalina/util
 ADD ServerInfo.properties ${CATALINA_HOME}/lib/org/apache/catalina/util/ServerInfo.properties

#remove all apps except ROOT
 RUN cd ${CATALINA_HOME}/webapps && \ 
   find -maxdepth 1 ! -name ROOT ! -name . -exec rm -rv {} \;
	
#make tomcat conf dir read only
 RUN chmod -R 400 ${CATALINA_HOME}/conf

WORKDIR /opt/tomcat

EXPOSE 8080
CMD ["catalina.sh", "run"]
